In [86]:
import pandas as pd

In [87]:
#scrapping data
df = pd.read_html('https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B9%D0%BE%D0%BD%D1%8B_%D0%B8_%D0%BF%D0%BE%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D1%8B')[0]

In [88]:
df

,№,Флаг,Герб,Название района[2]/поселения[3][4],Название cоответствующего внутригородского муниципального образования: муниципального округа / поселения / городского округа[5],Адми-нистра-тивныйокруг,"Пло-щадь,[6][7]км²","Насе-ление2020[8],чел.","Плот-ностьнасе-ления2020,чел. / км²","Пло-щадьжилого фонда(01.01.2010)[9],тыс. м²","Жил-площадьначело-века(01.01.2010),м²/чел."
0,1,NaN,NaN,Академический,Академический,ЮЗАО,583,↗110 038,18874.44,24670.0,227.0
1,2,NaN,NaN,Алексеевский,Алексеевский,СВАО,529,↗80 634,15242.72,16079.0,205.0
2,3,NaN,NaN,Алтуфьевский,Алтуфьевский,СВАО,325,↗57 697,17752.92,8393.0,155.0
3,4,NaN,NaN,Арбат,Арбат,ЦАО,211,↗36 308,17207.58,7310.0,260.0
4,5,NaN,NaN,Аэропорт,Аэропорт,САО,458,↗79 541,17367.03,19397.0,259.0
...,...,...,...,...,...,...,...,...,...,...,...
141,142,NaN,NaN,"Сосенское, поселение[Прим. 17]","Сосенское, поселение",НАО,6707,↗33 096,493.45,NaN,NaN
142,143,NaN,NaN,"Троицк, поселение[Прим. 18]","Троицк, городской округ",ТАО,1633,↗61 284,3752.85,NaN,NaN
143,144,NaN,NaN,"Филимонковское, поселение[Прим. 19]","Филимонковское, поселение",НАО,3577,↗8017,224.13,NaN,NaN
144,145,NaN,NaN,"Щаповское, поселение[Прим. 20]","Щаповское, поселение",ТАО,8606,↗9601,111.56,NaN,NaN
145,146,NaN,NaN,"Щербинка, поселение[Прим. 21]","Щербинка, городской округ",НАО,762,↗54 008,7087.66,NaN,NaN

In [89]:
#dropping excess columns
df = df.drop(columns = ['№', 'Флаг', 'Герб', 'Название района[2]/поселения[3][4]', 'Адми-нистра-тивныйокруг', 'Плот-ностьнасе-ления2020,чел. / км²', 'Пло-щадьжилого фонда(01.01.2010)[9],тыс. м²', 'Жил-площадьначело-века(01.01.2010),м²/чел.'])
df

,Название cоответствующего внутригородского муниципального образования: муниципального округа / поселения / городского округа[5],"Пло-щадь,[6][7]км²","Насе-ление2020[8],чел."
0,Академический,583,↗110 038
1,Алексеевский,529,↗80 634
2,Алтуфьевский,325,↗57 697
3,Арбат,211,↗36 308
4,Аэропорт,458,↗79 541
...,...,...,...
141,"Сосенское, поселение",6707,↗33 096
142,"Троицк, городской округ",1633,↗61 284
143,"Филимонковское, поселение",3577,↗8017
144,"Щаповское, поселение",8606,↗9601
145,"Щербинка, городской округ",762,↗54 008

In [90]:
#renaming columns
df = df.rename(columns = {'Название cоответствующего внутригородского муниципального образования: муниципального округа / поселения / городского округа[5]':'Borough','Насе-ление2020[8],чел.':'Population', 'Пло-щадь,[6][7]км²':'Area' })

In [91]:
df

                       Borough  Area Population
0                Академический   583   ↗110 038
1                 Алексеевский   529    ↗80 634
2                 Алтуфьевский   325    ↗57 697
3                        Арбат   211    ↗36 308
4                     Аэропорт   458    ↗79 541
..                         ...   ...        ...
141       Сосенское, поселение  6707    ↗33 096
142    Троицк, городской округ  1633    ↗61 284
143  Филимонковское, поселение  3577      ↗8017
144       Щаповское, поселение  8606      ↗9601
145  Щербинка, городской округ   762    ↗54 008

[146 rows x 3 columns]

In [92]:
c = df.Borough.tolist()
c

['Академический',
 'Алексеевский',
 'Алтуфьевский',
 'Арбат',
 'Аэропорт',
 'Бабушкинский',
 'Басманный',
 'Беговой',
 'Бескудниковский',
 'Бибирево',
 'Бирюлёво Восточное',
 'Бирюлёво Западное',
 'Богородское',
 'Братеево',
 'Бутырский',
 'Вешняки',
 'Внуково',
 'Войковский',
 'Восточное Дегунино',
 'Восточное Измайлово',
 'Восточный',
 'Выхино-Жулебино',
 'Гагаринский',
 'Головинский',
 'Гольяново',
 'Даниловский',
 'Дмитровский',
 'Донской',
 'Дорогомилово',
 'Замоскворечье',
 'Западное Дегунино',
 'Зюзино',
 'Зябликово',
 'Ивановское',
 'Измайлово',
 'Капотня',
 'Коньково',
 'Коптево',
 'Косино-Ухтомский',
 'Котловка',
 'Красносельский',
 'Крылатское',
 'Крюково',
 'Кузьминки',
 'Кунцево',
 'Куркино',
 'Левобережный',
 'Лефортово',
 'Лианозово',
 'Ломоносовский',
 'Лосиноостровский',
 'Люблино',
 'Марфино',
 'Марьина Роща',
 'Марьино',
 'Матушкино',
 'Метрогородок',
 'Мещанский',
 'Митино',
 'Можайский',
 'Молжаниновский',
 'Москворечье-Сабурово',
 'Нагатино-Садовники',
 'Нагатинский Затон',
 'Нагорный',
 'Некрасовка',
 'Нижегородский',
 'Новогиреево',
 'Новокосино',
 'Ново-Переделкино',
 'Обручевский',
 'Орехово-Борисово Северное',
 'Орехово-Борисово Южное',
 'Останкинский',
 'Отрадное',
 'Очаково-Матвеевское',
 'Перово',
 'Печатники',
 'Покровское-Стрешнево',
 'Преображенское',
 'Пресненский',
 'Проспект Вернадского',
 'Раменки',
 'Ростокино',
 'Рязанский',
 'Савёлки',
 'Савёловский',
 'Свиблово',
 'Северное Бутово',
 'Северное Измайлово',
 'Северное Медведково',
 'Северное Тушино',
 'Северный',
 'Силино',
 'Сокол',
 'Соколиная Гора',
 'Сокольники',
 'Солнцево',
 'Старое Крюково',
 'Строгино',
 'Таганский',
 'Тверской',
 'Текстильщики',
 'Тёплый Стан',
 'Тимирязевский',
 'Тропарёво-Никулино',
 'Филёвский Парк',
 'Фили-Давыдково',
 'Хамовники',
 'Ховрино',
 'Хорошёво-Мнёвники',
 'Хорошёвский',
 'Царицыно',
 'Черёмушки',
 'Чертаново Северное',
 'Чертаново Центральное',
 'Чертаново Южное',
 'Щукино',
 'Южное Бутово',
 'Южное Медведково',
 'Южное Тушино',
 'Южнопортовый',
 'Якиманка',
 'Ярославский',
 'Ясенево',
 'Внуковское, поселение',
 'Вороновское, поселение',
 'Воскресенское, поселение',
 'Десёновское, поселение',
 'Киевский, поселение',
 'Клёновское, поселение',
 'Кокошкино, поселение',
 'Краснопахорское, поселение',
 'Марушкинское, поселение',
 'Михайлово-Ярцевское, поселение',
 'Московский, поселение',
 'Мосрентген, поселение',
 'Новофёдоровское, поселение',
 'Первомайское, поселение',
 'Роговское, поселение',
 'Рязановское, поселение',
 'Сосенское, поселение',
 'Троицк, городской округ',
 'Филимонковское, поселение',
 'Щаповское, поселение',
 'Щербинка, городской округ']

In [93]:
#translating borough names (translated manually)
boroughs_en = ['Akademicheskij',
 'Alekseevskij',
 'Altufevskij',
 'Arbat',
 'Aeroport',
 'Babushkinskij',
 'Basmannyj',
 'Begovoj',
 'Beskudnikovskij',
 'Bibirevo',
 'Biryulyovo Vostochnoe',
 'Biryulyovo Zapadnoe',
 'Bogorodskoe',
 'Brateevo',
 'Butyrskij',
 'Veshnyaki',
 'Vnukovo',
 'Vojkovskij',
 'Vostochnoe Degunino',
 'Vostochnoe Izmajlovo',
 'Vostochnyj',
 'Vyhino-ZHulebino',
 'Gagarinskij',
 'Golovinskij',
 'Golyanovo',
 'Danilovskij',
 'Dmitrovskij',
 'Donskoj',
 'Dorogomilovo',
 'Zamoskvoreche',
 'Zapadnoe Degunino',
 'Zyuzino',
 'Zyablikovo',
 'Ivanovskoe',
 'Izmajlovo',
 'Kapotnya',
 'Konkovo',
 'Koptevo',
 'Kosino-Uhtomskij',
 'Kotlovka',
 'Krasnoselskij',
 'Krylatskoe',
 'Kryukovo',
 'Kuzminki',
 'Kuncevo',
 'Kurkino',
 'Levoberezhnyj',
 'Lefortovo',
 'Lianozovo',
 'Lomonosovskij',
 'Losinoostrovskij',
 'Lyublino',
 'Marfino',
 'Marina Roshcha',
 'Marino',
 'Matushkino',
 'Metrogorodok',
 'Meshchanskij',
 'Mitino',
 'Mozhajskij',
 'Molzhaninovskij',
 'Moskvoreche-Saburovo',
 'Nagatino-Sadovniki',
 'Nagatinskij Zaton',
 'Nagornyj',
 'Nekrasovka',
 'Nizhegorodskij',
 'Novogireevo',
 'Novokosino',
 'Novo-Peredelkino',
 'Obruchevskij',
 'Orekhovo-Borisovo Severnoe',
 'Orekhovo-Borisovo YUzhnoe',
 'Ostankinskij',
 'Otradnoe',
 'Ochakovo-Matveevskoe',
 'Perovo',
 'Pechatniki',
 'Pokrovskoe-Streshnevo',
 'Preobrazhenskoe',
 'Presnenskij',
 'Prospekt Vernadskogo',
 'Ramenki',
 'Rostokino',
 'Ryazanskij',
 'Savyolki',
 'Savyolovskij',
 'Sviblovo',
 'Severnoe Butovo',
 'Severnoe Izmajlovo',
 'Severnoe Medvedkovo',
 'Severnoe Tushino',
 'Severnyj',
 'Silino',
 'Sokol',
 'Sokolinaya Gora',
 'Sokolniki',
 'Solncevo',
 'Staroe Kryukovo',
 'Strogino',
 'Taganskij',
 'Tverskoj',
 'Tekstilshchiki',
 'Tyoplyj Stan',
 'Timiryazevskij',
 'Troparyovo-Nikulino',
 'Filyovskij Park',
 'Fili-Davydkovo',
 'Hamovniki',
 'Hovrino',
 'Horoshyovo-Mnyovniki',
 'Horoshyovskij',
 'Caricyno',
 'CHeryomushki',
 'CHertanovo Severnoe',
 'CHertanovo Centralnoe',
 'CHertanovo YUzhnoe',
 'SHCHukino',
 'YUzhnoe Butovo',
 'YUzhnoe Medvedkovo',
 'YUzhnoe Tushino',
 'YUzhnoportovyj',
 'YAkimanka',
 'YAroslavskij',
 'YAsenevo',
 'Vnukovskoe',
 'Voronovskoe, poselenie',
 'Voskresenskoe, poselenie',
 'Desyonovskoe, poselenie',
 'Kievskij, poselenie',
 'Klyonovskoe, poselenie',
 'Kokoshkino, poselenie',
 'Krasnopahorskoe, poselenie',
 'Marushkinskoe, poselenie',
 'Mihajlovo-YArcevskoe, poselenie',
 'Moskovskij, poselenie',
 'Mosrentgen, poselenie',
 'Novofyodorovskoe, poselenie',
 'Pervomajskoe, poselenie',
 'Rogovskoe, poselenie',
 'Ryazanovskoe, poselenie',
 'Sosenskoe, poselenie',
 'Troick',
 'Filimonkovskoe, poselenie',
 'SHCHapovskoe, poselenie',
 'SHCHerbinka, gorodskoj okrug']

In [94]:
df.Borough = boroughs_en
df

                          Borough  Area Population
0                  Akademicheskij   583   ↗110 038
1                    Alekseevskij   529    ↗80 634
2                     Altufevskij   325    ↗57 697
3                           Arbat   211    ↗36 308
4                        Aeroport   458    ↗79 541
..                            ...   ...        ...
141          Sosenskoe, poselenie  6707    ↗33 096
142                        Troick  1633    ↗61 284
143     Filimonkovskoe, poselenie  3577      ↗8017
144       SHCHapovskoe, poselenie  8606      ↗9601
145  SHCHerbinka, gorodskoj okrug   762    ↗54 008

[146 rows x 3 columns]

In [95]:
#cleaning Population column
a = df.Population.tolist()
b = []
for i in a:
    i = i.replace("↗", "").replace(u"\xa0", "")
    i = int(i)
    b.append(i)
df.Population = b

In [96]:
#opening my private yandex api key
import json

with open('C:/Users/Кирилл/api_key_yandex.json', mode='r') as key_file:
    key = json.loads(key_file.read())['key']

In [97]:
#parcing latitude and longtitude data by yandex api (good works for russain adresses), 'c' is a list of boroughs in russian from cell 7.
import requests
latlon_data = {'Longitude':[], 'Latitute':[]}
for i in c:
    coor = requests.get('https://geocode-maps.yandex.ru/1.x/?geocode='+ i + '%2C+Район%2C+Москва&apikey=' + key+ '&lang=ru-RU&format=json&results=1')
    coor = coor.json()
    d = coor.get('response').get('GeoObjectCollection').get('featureMember')[0].get('GeoObject').get('Point').get('pos')
    Lon,Lat = d.split()
    latlon_data['Longitude'].append(Lon)
    latlon_data['Latitute'].append(Lat)
latlon_data

{'Longitude': ['37.572684',
  '37.650163',
  '37.582278',
  '37.590003',
  '37.542599',
  '37.665812',
  '37.671229',
  '37.566297',
  '37.554708',
  '37.6077',
  '37.678649',
  '37.639644',
  '37.703415',
  '37.765058',
  '37.589204',
  '37.815184',
  '37.296685',
  '37.497342',
  '37.558841',
  '37.821804',
  '37.862076',
  '37.824553',
  '37.558535',
  '37.510601',
  '37.799867',
  '37.64277',
  '37.52863',
  '37.61839',
  '37.547656',
  '37.63429',
  '37.518937',
  '37.589608',
  '37.746076',
  '37.824005',
  '37.772783',
  '37.799724',
  '37.530588',
  '37.526277',
  '37.86345',
  '37.597199',
  '37.654574',
  '37.423716',
  '37.176122',
  '37.773547',
  '37.398482',
  '37.387379',
  '37.465937',
  '37.704817',
  '37.570007',
  '37.533239',
  '37.69419',
  '37.748726',
  '37.588745',
  '37.614374',
  '37.744774',
  '37.200116',
  '37.755832',
  '37.628801',
  '37.365828',
  '37.422755',
  '37.380237',
  '37.671139',
  '37.64171',
  '37.681568',
  '37.61547',
  '37.940032',
  '37.723807',
  '37.804108',
  '37.865777',
  '37.357169',
  '37.518479',
  '37.704817',
  '37.733132',
  '37.621705',
  '37.600262',
  '37.448554',
  '37.767456',
  '37.723807',
  '37.445779',
  '37.722487',
  '37.562389',
  '37.498635',
  '37.51379',
  '37.652948',
  '37.7676',
  '37.238016',
  '37.570914',
  '37.647711',
  '37.570519',
  '37.805221',
  '37.655634',
  '37.428118',
  '37.546695',
  '37.168244',
  '37.504376',
  '37.730625',
  '37.677158',
  '37.40168',
  '37.199056',
  '37.402695',
  '37.666971',
  '37.606918',
  '37.734371',
  '37.489877',
  '37.557071',
  '37.468488',
  '37.494584',
  '37.469359',
  '37.574525',
  '37.489491',
  '37.492078',
  '37.528208',
  '37.652768',
  '37.561347',
  '37.605113',
  '37.604098',
  '37.600361',
  '37.473519',
  '37.531523',
  '37.637389',
  '37.431423',
  '37.670474',
  '37.607565',
  '37.69746',
  '37.534577',
  '37.290298',
  '37.123131',
  '37.4432',
  '37.36661',
  '36.88346',
  '37.326743',
  '37.169843',
  '37.270661',
  '37.208273',
  '37.139696',
  '37.368901',
  '37.473797',
  '36.918863',
  '37.218334',
  '37.054742',
  '37.495707',
  '37.465892',
  '37.295014',
  '37.322368',
  '37.380848',
  '37.567653'],
 'Latitute': ['55.688005',
  '55.812949',
  '55.879849',
  '55.751138',
  '55.803312',
  '55.867081',
  '55.766567',
  '55.782871',
  '55.866622',
  '55.894768',
  '55.594585',
  '55.58786',
  '55.819241',
  '55.633434',
  '55.814123',
  '55.730771',
  '55.610845',
  '55.827247',
  '55.884277',
  '55.795818',
  '55.817952',
  '55.696357',
  '55.698041',
  '55.846765',
  '55.820804',
  '55.706457',
  '55.891027',
  '55.697798',
  '55.739468',
  '55.734157',
  '55.872157',
  '55.654066',
  '55.620423',
  '55.771479',
  '55.783681',
  '55.63784',
  '55.643414',
  '55.831211',
  '55.717061',
  '55.676209',
  '55.778041',
  '55.763194',
  '55.96933',
  '55.69864',
  '55.74261',
  '55.891209',
  '55.865419',
  '55.753635',
  '55.898487',
  '55.678778',
  '55.881268',
  '55.677717',
  '55.830002',
  '55.796931',
  '55.652664',
  '56.005103',
  '55.823616',
  '55.780066',
  '55.84537',
  '55.717634',
  '55.936812',
  '55.642692',
  '55.671422',
  '55.682849',
  '55.664659',
  '55.698259',
  '55.728423',
  '55.748154',
  '55.742245',
  '55.646081',
  '55.660917',
  '55.618278',
  '55.604264',
  '55.81908',
  '55.86206',
  '55.689649',
  '55.751994',
  '55.685158',
  '55.823823',
  '55.797296',
  '55.763432',
  '55.678407',
  '55.707152',
  '55.83527',
  '55.724718',
  '55.989915',
  '55.799694',
  '55.851839',
  '55.568914',
  '55.806843',
  '55.888331',
  '55.861479',
  '55.929757',
  '55.999007',
  '55.805938',
  '55.772775',
  '55.799947',
  '55.645918',
  '55.980895',
  '55.803783',
  '55.74001',
  '55.770127',
  '55.708917',
  '55.631427',
  '55.825527',
  '55.660318',
  '55.749805',
  '55.727136',
  '55.729199',
  '55.869041',
  '55.777707',
  '55.782289',
  '55.627387',
  '55.664649',
  '55.632205',
  '55.61388',
  '55.591889',
  '55.80059',
  '55.542396',
  '55.871248',
  '55.843434',
  '55.713086',
  '55.730826',
  '55.862858',
  '55.607514',
  '55.6335',
  '55.323874',
  '55.527326',
  '55.499571',
  '55.394878',
  '55.314208',
  '55.600165',
  '55.421496',
  '55.59516',
  '55.397577',
  '55.608404',
  '55.621074',
  '55.493502',
  '55.519723',
  '55.220064',
  '55.482373',
  '55.57833',
  '55.481546',
  '55.570014',
  '55.391631',
  '55.507525']}

In [98]:
#adding data to our dataframe
latlon_data = pd.DataFrame(latlon_data)
df = pd.concat([df, latlon_data], axis=1)

In [99]:
df

                          Borough  Area  Population  Longitude   Latitute
0                  Akademicheskij   583      110038  37.572684  55.688005
1                    Alekseevskij   529       80634  37.650163  55.812949
2                     Altufevskij   325       57697  37.582278  55.879849
3                           Arbat   211       36308  37.590003  55.751138
4                        Aeroport   458       79541  37.542599  55.803312
..                            ...   ...         ...        ...        ...
141          Sosenskoe, poselenie  6707       33096  37.465892   55.57833
142                        Troick  1633       61284  37.295014  55.481546
143     Filimonkovskoe, poselenie  3577        8017  37.322368  55.570014
144       SHCHapovskoe, poselenie  8606        9601  37.380848  55.391631
145  SHCHerbinka, gorodskoj okrug   762       54008  37.567653  55.507525

[146 rows x 5 columns]

In [100]:
#cleaning Area column
df.Area = df.Area.div(100)
df

                          Borough   Area  Population  Longitude   Latitute
0                  Akademicheskij   5.83      110038  37.572684  55.688005
1                    Alekseevskij   5.29       80634  37.650163  55.812949
2                     Altufevskij   3.25       57697  37.582278  55.879849
3                           Arbat   2.11       36308  37.590003  55.751138
4                        Aeroport   4.58       79541  37.542599  55.803312
..                            ...    ...         ...        ...        ...
141          Sosenskoe, poselenie  67.07       33096  37.465892   55.57833
142                        Troick  16.33       61284  37.295014  55.481546
143     Filimonkovskoe, poselenie  35.77        8017  37.322368  55.570014
144       SHCHapovskoe, poselenie  86.06        9601  37.380848  55.391631
145  SHCHerbinka, gorodskoj okrug   7.62       54008  37.567653  55.507525

[146 rows x 5 columns]

In [101]:
with open('C:/Users/Кирилл/id_foursquare.json', mode='r') as id_file:
    CLIENT_ID = json.loads(id_file.read())['key'] 
with open('C:/Users/Кирилл/secret_foursquare.json', mode='r') as secret_file:
    CLIENT_SECRET = json.loads(secret_file.read())['key']
VERSION = '20180605' # Foursquare API version
LIMIT = 2000 # A default Foursquare API limit value

In [102]:
sheeeeet_data = {'Number of places':[]}

In [103]:
#parcing info about places number
for i in range(146):
    neighborhood_latitude = df.loc[i, 'Latitute'] # neighborhood latitude value
    neighborhood_longitude = df.loc[i, 'Longitude'] # neighborhood longitude value
    radius = df.loc[i, 'Area']*1000**0.5
    url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
        CLIENT_ID, 
        CLIENT_SECRET, 
        VERSION, 
        neighborhood_latitude, 
        neighborhood_longitude, 
        radius, 
        LIMIT)
    results = requests.get(url).json()
    res = results.get('response').get('totalResults')
    sheeeeet_data['Number of places'].append(res)

In [104]:
#adding data to our dataframe
sheeeeet_data = pd.DataFrame(sheeeeet_data)
df = pd.concat([df, sheeeeet_data], axis=1)
df

,Borough,Area,Population,Longitude,Latitute,Number of places
0,Akademicheskij,5.83,110038,37.572684,55.688005,15
1,Alekseevskij,5.29,80634,37.650163,55.812949,3
2,Altufevskij,3.25,57697,37.582278,55.879849,2
3,Arbat,2.11,36308,37.590003,55.751138,1
4,Aeroport,4.58,79541,37.542599,55.803312,0
...,...,...,...,...,...,...
141,"Sosenskoe, poselenie",67.07,33096,37.465892,55.57833,55
142,Troick,16.33,61284,37.295014,55.481546,4
143,"Filimonkovskoe, poselenie",35.77,8017,37.322368,55.570014,0
144,"SHCHapovskoe, poselenie",86.06,9601,37.380848,55.391631,6
145,"SHCHerbinka, gorodskoj okrug",7.62,54008,37.567653,55.507525,4

In [105]:
sad_data = {'per thousand people':[]}

In [106]:
for i in range(146):
    sad_data['per thousand people'].append(round(df.loc[i, 'Population']/1000 / df.loc[i, 'Number of places'], 2))

<ipython-input-106-1413d87c65d9>:2: RuntimeWarning: divide by zero encountered in double_scalars
  sad_data['per thousand people'].append(round(df.loc[i, 'Population']/1000 / df.loc[i, 'Number of places'], 2))

In [107]:
sad_data = pd.DataFrame(sad_data)
df = pd.concat([df, sad_data], axis=1)
df

,Borough,Area,Population,Longitude,Latitute,Number of places,per thousand people
0,Akademicheskij,5.83,110038,37.572684,55.688005,15,7.34
1,Alekseevskij,5.29,80634,37.650163,55.812949,3,26.88
2,Altufevskij,3.25,57697,37.582278,55.879849,2,28.85
3,Arbat,2.11,36308,37.590003,55.751138,1,36.31
4,Aeroport,4.58,79541,37.542599,55.803312,0,inf
...,...,...,...,...,...,...,...
141,"Sosenskoe, poselenie",67.07,33096,37.465892,55.57833,55,0.60
142,Troick,16.33,61284,37.295014,55.481546,4,15.32
143,"Filimonkovskoe, poselenie",35.77,8017,37.322368,55.570014,0,inf
144,"SHCHapovskoe, poselenie",86.06,9601,37.380848,55.391631,6,1.60
145,"SHCHerbinka, gorodskoj okrug",7.62,54008,37.567653,55.507525,4,13.50